sets openoffice to unsupported & refactors in fail

diff --git a/bin/list-all b/bin/list-all
--- a/bin/list-all
+++ b/bin/list-all
@@ -12,29 +12,40 @@ BIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 readonly BIN_DIR
 
 declare THIS_PLUGIN_DIR PRODUCT_NAME
-readonly INCLUDE_SRC="${INCLUDE_SRC:-1}"
+readonly INCLUDE_SRC="${INCLUDE_SRC:-false}"
 THIS_PLUGIN_DIR="$(dirname "${BIN_DIR}")"
 readonly THIS_PLUGIN_DIR
 readonly THIS_PLUGIN_LIB_DIR="${THIS_PLUGIN_DIR}/lib"
-PRODUCT_NAME="$(basename "${THIS_PLUGIN_DIR}")"
+FOLDER_NAME="$(basename "${THIS_PLUGIN_DIR}")"
+PRODUCT_NAME="${PRODUCT_NAME:-$FOLDER_NAME}"
 readonly PRODUCT_NAME
+TOOL_PRODUCT_NAME="$(basename "$(dirname "${ASDF_INSTALL_PATH}")")"
+readonly TOOL_PRODUCT_NAME
+readonly TOOL_NAME="apache"
 
-{ command -vp curl >/dev/null; } 2>&1 || (echo >&2 'Missing curl' && exit 1)
-{ command -v parallel >/dev/null; } 2>&1 || (echo >&2 'Missing gnu parallel' && exit 1)
+curl_opts=(-fsSL)
+
+fail() {
+  echo -e "asdf-$TOOL_NAME|$TOOL_PRODUCT_NAME: $*"
+  exit 1
+}
+
+command -vp curl >/dev/null 2>&1 || fail 'Missing curl'
+command -v parallel >/dev/null 2>&1 || fail 'Missing gnu parallel'
 
 releases_path() {
-  local product_name="${1}"
-  local version="${2:-}"
+  local -r product_name="${1}"
+  local -r version="${2:-}"
   echo "https://archive.apache.org/dist/${product_name}/${version}"
 }
 
 list_release_folders() {
-  local product_name="$1"
-  local releases_path="$2"
-  local curl_cmd cmd raw_versions trimmed_versions grep_str
-  curl_cmd="$(command -vp curl)"
-  cmd="${curl_cmd} -fsS"
+  local -r product_name="$1"
+  local -r releases_path="$2"
+  local -r curl_cmd="$(command -vp curl)"
+  local -r cmd="${curl_cmd} ${curl_opts[*]}"
 
+  local raw_versions trimmed_versions grep_str
   raw_versions="$(eval "${cmd}" "${releases_path}")"
   grep_str='href=".+\/">'
   trimmed_versions="$(echo "${raw_versions}" | grep -oE "${grep_str}" | sed -E 's/.+"(apache-)?(.+)">/\2/g' | cut -d/ -f1)"
@@ -42,12 +53,13 @@ list_release_folders() {
 }
 
 list_versions() {
-  local product_name="$1"
-  local releases_path="$2"
-  local curl_cmd cmd raw_versions trimmed_versions grep_str
-  curl_cmd="$(command -vp curl)"
-  cmd="${curl_cmd} -fsS"
+  local -r product_name="$1"
+  local -r releases_path="$2"
 
+  local -r curl_cmd="$(command -vp curl)"
+  local -r cmd="${curl_cmd} ${curl_opts[*]}"
+
+  local raw_versions trimmed_versions grep_str
   raw_versions="$(eval "${cmd}" "${releases_path}")"
   grep_str='href=".*'"(${product_name})?"'.+(tgz|tar.gz)">'
   trimmed_versions="$(echo "${raw_versions}" | grep -oE "${grep_str}" | sed -E 's/.+"(apache-)?(.+)">/\2/g' | cut -d/ -f1)"
@@ -66,9 +78,9 @@ sort_sub_versions() {
 }
 
 get_sub_versions() {
-  local product_name="$1"
-  local include_src="$2"
-  local version="$3"
+  local -r product_name="$1"
+  local -r include_src="$2"
+  local -r version="$3"
   local sub_release_path file_names
   local product_lib_file="${THIS_PLUGIN_LIB_DIR}/${product_name}.sh"
   sub_release_path="$(releases_path "${product_name}" "${version}/")"
@@ -78,7 +90,7 @@ get_sub_versions() {
     . "${product_lib_file}"
     list_sub_versions "${file_names}" "${include_src}"
   else
-    if [ "${include_src}" = "0" ]; then
+    if [ "${include_src}" = "false" ]; then
       printf "%s" "${file_names}" |
         grep -E 'tgz|tar\.gz' |
         sed -E 's/'"${product_name}"'-(.+)(\.tgz|\.tar.gz)/\1/g' |
@@ -92,17 +104,31 @@ get_sub_versions() {
   fi
 }
 
-export -f get_sub_versions
-export -f releases_path
-export -f list_versions
-export -f sort_top_level_versions
-export SHELLOPTS
-export THIS_PLUGIN_LIB_DIR
-release_path="$(releases_path "${PRODUCT_NAME}")"
-init_versions="$(list_release_folders "${PRODUCT_NAME}" "${release_path}")"
-count="$(wc -l <<<"${init_versions}" | tr -d " ")"
-# shellcheck disable=SC2005
-echo "$(parallel --jobs "${count}" get_sub_versions "${PRODUCT_NAME}" "1" <<<"${init_versions}")" | sort_sub_versions | tr "\n" " "
+get_versions() {
+  local -r product_name="${1}"
+  local -r include_src="${2:-false}"
+
+  export -f get_sub_versions
+  export -f releases_path
+  export -f list_versions
+  export -f sort_top_level_versions
+
+  release_path="$(releases_path "${product_name}")"
+  init_versions="$(list_release_folders "${product_name}" "${release_path}")"
+  count="$(wc -l <<<"${init_versions}")"
+
+  # shellcheck disable=SC2005 # not sure if the echo is needed TODO
+  echo "$(parallel --jobs "$count" get_sub_versions "${product_name}" "${include_src}" <<<"${init_versions}")" | sort_sub_versions | tr "\n" " "
+}
+
+case "${PRODUCT_NAME}" in
+openoffice)
+  fail "Not supported ${PRODUCT_NAME}"
+  ;;
+*)
+  get_versions "${PRODUCT_NAME}" "${INCLUDE_SRC}"
+  ;;
+esac
 
 if [ -n "${DEBUG}" ]; then
   set +x
