adds the the sub-versinos to the install

diff --git a/bin/list-all b/bin/list-all
--- a/bin/list-all
+++ b/bin/list-all
@@ -3,25 +3,56 @@ set -Eeuo pipefail
 
 DEBUG="${DEBUG:-}"
 
+VERSION="${1:-}"
+
 if [ -n "${DEBUG}" ]; then
   set -x
 fi
 
-releases_path="https://archive.apache.org/dist/flink/"
-curl_cmd="$(command -vp curl)"
-cmd="${curl_cmd} -fsS"
+if [ -n "${VERSION}" ]; then
+  VERSION="flink-${VERSION}/"
+fi
+
+command -vp curl 2>&1 >/dev/null || (>&2 echo 'Missing curl' && exit 1)
+command -v parallel 2>&1 >/dev/null || (>&2 echo 'Missing gnu parallel' && exit 1)
+
+releases_path() {
+  local version="${1:-}"
+  echo "https://archive.apache.org/dist/flink/${version}"
+}
+
+list_versions() {
+  local releases_path="$1"
+  local curl_cmd="$(command -vp curl)"
+  local cmd="${curl_cmd} -fsS"
+
+  # Fetch all tag names, and get only second column. Then remove all unnecesary characters.
+  local raw_versions="$(eval $cmd $releases_path)"
+  local trimmed_versions="$(echo "${raw_versions}" | grep -oE 'href=".*flink.+(\/|tgz)">' | sed -E 's/.+"(.+)">/\1/g' | cut -d/ -f1  )"
+  echo "${trimmed_versions}" | sort_top_level_versions
+}
 
 # stolen from https://github.com/rbenv/ruby-build/pull/631/files#diff-fdcfb8a18714b33b07529b7d02b54f1dR942
-function sort_versions() {
+sort_top_level_versions() {
   sed 'h; s/[+-]/./g; s/.p\([[:digit:]]\)/.z\1/; s/$/.z/; G; s/\n/ /' | \
     LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n | awk '{print $2}'
 }
 
-# Fetch all tag names, and get only second column. Then remove all unnecesary characters.
-raw_versions="$(eval $cmd $releases_path)"
-greped_versions=$(echo "${raw_versions}" | grep -o '">flink.*/<' | grep -o 'flink.*' | cut -d/ -f1 | cut -d- -f2-)
-versions=$(echo "$greped_versions" | sort_versions)
-echo $versions
+release_path="$(releases_path "${VERSION}")"
+init_versions="$(list_versions "${release_path}")"
+count="$(wc -l <<<"${init_versions}")"
+get_sub_versions() {
+  local version="${1}"
+  local sub_release_path="$(releases_path "${version}/")"
+  local file_names="$(list_versions "${sub_release_path}")"
+  printf "${file_names}" | grep 'tgz' | sed -E 's/(.+).tgz/\1/g'
+}
+export -f get_sub_versions
+export -f releases_path
+export -f list_versions
+export -f sort_top_level_versions
+
+echo "$(parallel --jobs $count get_sub_versions <<< "${init_versions}")"
 
 if [ ! -z "${DEBUG}" ]; then
   set +x
