sets openoffice to unsupported & refactors in fail

diff --git a/bin/list-all b/bin/list-all
--- a/bin/list-all
+++ b/bin/list-all
@@ -16,8 +16,17 @@ fi
 
 readonly PRODUCT_NAME="$(basename "$(dirname ${THIS_DIR})")"
 
-command -vp curl 2>&1 >/dev/null || (>&2 echo 'Missing curl' && exit 1)
-command -v parallel 2>&1 >/dev/null || (>&2 echo 'Missing gnu parallel' && exit 1)
+readonly TOOL_NAME="apache-${PRODUCT_NAME}"
+
+fail() {
+  echo -e "asdf-$TOOL_NAME: $*"
+  exit 1
+}
+
+curl_opts=(-fsSL)
+
+command -vp curl 2>&1 >/dev/null || fail 'Missing curl'
+command -v parallel 2>&1 >/dev/null || fail 'Missing gnu parallel'
 
 releases_path() {
   local product_name="${1}"
@@ -29,7 +38,7 @@ list_versions() {
   local product_name="$1"
   local releases_path="$2"
   local curl_cmd="$(command -vp curl)"
-  local cmd="${curl_cmd} -fsS"
+  local cmd="${curl_cmd} "${curl_opts}""
 
   local grep_str='href=".*'"(${product_name})?"'.+(\/|tgz|tar.gz)">'
 
@@ -55,20 +64,33 @@ get_sub_versions() {
   local version="$2"
   local sub_release_path="$(releases_path "${product_name}" "${version}/")"
   local file_names="$(list_versions "${product_name}" "${sub_release_path}")"
-  printf "${file_names}" | grep -E 'tgz|tar.gz' | sed -E 's/'"${product_name}"'-(.+)(.tgz|.tar.gz)/\1/g'
+  printf "%s" "${file_names}" | grep -E 'tgz|tar.gz' | sed -E 's/'"${product_name}"'-(.+)(.tgz|.tar.gz)/\1/g'
 }
 
-export -f get_sub_versions
-export -f releases_path
-export -f list_versions
-export -f sort_top_level_versions
+get_versions() {
+  local product_name="${1}"
 
-release_path="$(releases_path "${PRODUCT_NAME}")"
-init_versions="$(list_versions "${PRODUCT_NAME}" "${release_path}")"
-count="$(wc -l <<<"${init_versions}")"
+  export -f get_sub_versions
+  export -f releases_path
+  export -f list_versions
+  export -f sort_top_level_versions
 
-echo "$(parallel --jobs $count get_sub_versions "${PRODUCT_NAME}" <<< "${init_versions}")" |  sort_sub_versions | tr "\n" " "
+  release_path="$(releases_path "${product_name}")"
+  init_versions="$(list_versions "${product_name}" "${release_path}")"
+  count="$(wc -l <<<"${init_versions}")"
 
-if [ ! -z "${DEBUG}" ]; then
+  echo "$(parallel --jobs $count get_sub_versions "${PRODUCT_NAME}" <<< "${init_versions}")" |  sort_sub_versions | tr "\n" " "
+}
+
+case "${PRODUCT_NAME}" in
+  openoffice)
+    fail "Not supported ${PRODUCT_NAME}"
+    ;;
+  *)
+    get_versions "${PRODUCT_NAME}"
+    ;;
+esac
+
+if [ -n "${DEBUG}" ]; then
   set +x
 fi
